"""Run a battery of world-model-join capability cases against the LIVE KnowledgeReasoner + seeded Postgres,
and report a capability MAP: what the world model can actually join / filter / compute, what silently
breaks, and what it (correctly) can't do. Cases are DB-grounded (expected values computed from the live
world DB), generated by the world-model-capability-suite workflow into a JSON file.

  KB_PG_PASSWORD must be set (autoloaded from .env). Loads the model ONCE.
  python -m regress.world_capability [cases.json]
"""
from __future__ import annotations

import collections
import json
import os
import sys
import warnings

warnings.filterwarnings("ignore")


def _coerce(v):
    v = v.strip()
    try:
        return int(v)
    except ValueError:
        try:
            return float(v)
        except ValueError:
            return v


def csv_to_table(name, csv):
    lines = [ln for ln in csv.replace("\r", "").split("\n") if ln.strip() != ""]
    cols = [c.strip() for c in lines[0].split(",")]
    rows = [[_coerce(x) for x in ln.split(",")] for ln in lines[1:]]
    return {"name": name, "columns": cols, "rows": rows}


def _num(v):
    try:
        return round(float(str(v).replace(",", "").lstrip("$").rstrip("%")), 2)
    except (ValueError, TypeError):
        return None


def serve_case(Q, case, sub):
    tables = [csv_to_table(t["name"], t["csv"]) for t in case["tables"]]
    try:
        r = Q.serve(tables, case["question"], sub)
    except Exception as e:                                       # noqa: BLE001
        return {"error": f"{type(e).__name__}: {e}"}
    res = r.get("result") or {}
    rows = res.get("rows") or []
    scalar = rows[0][0] if (len(rows) == 1 and rows and len(rows[0]) == 1) else None
    return {"clarify": bool(r.get("clarify")), "rows": rows, "scalar": scalar,
            "sql": r.get("sql"), "model": (r.get("model") or "")[:60], "error": r.get("error")}


def classify(case, out):
    """Return (verdict, detail). verdict in {PASS, FAIL, CLARIFY, EMPTY, ERROR, ANSWERED}."""
    if out.get("error"):
        return "ERROR", out["error"][:80]
    if out.get("clarify"):
        return "CLARIFY", "engine asked to clarify"
    kind = case.get("expected_kind")
    rows = out.get("rows") or []
    flat = {str(v).strip().lower() for r in rows for v in r}
    if kind == "scalar":
        want = _num(case.get("expected_value"))
        got = _num(out.get("scalar"))
        return ("PASS" if (got is not None and want is not None and abs(got - want) < 0.5) else "FAIL",
                f"got {out.get('scalar')} want {case.get('expected_value')}")
    if kind == "contains":
        want = [w.strip().lower() for w in str(case.get("expected_value", "")).split(",") if w.strip()]
        miss = [w for w in want if not any(w in f or _num(w) == _num(v) for f in flat for v in [f])]
        return ("PASS" if rows and not miss else "FAIL", f"missing {miss}" if miss else "ok")
    if kind == "nonempty":
        return ("PASS" if rows else "EMPTY", f"{len(rows)} rows")
    if kind in ("unsupported", "clarify"):
        # correct behavior = it did NOT confidently answer with a plausible scalar
        if not rows:
            return "PASS", "no confident answer (empty) — as expected for unsupported"
        return "ANSWERED", f"produced an answer {out.get('scalar') or rows[:1]} (expected unsupported/clarify)"
    return "ANSWERED", f"scalar={out.get('scalar')} rows={len(rows)}"


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "world_cases_generated.json")
    cases = json.load(open(path, encoding="utf-8"))
    print(f"loaded {len(cases)} cases from {os.path.basename(path)}")
    import engine.config  # noqa: F401 — autoloads .env so KB_PG_PASSWORD is present
    if not os.environ.get("KB_PG_PASSWORD"):
        print("KB_PG_PASSWORD not set — cannot run the world model"); sys.exit(2)
    print("loading KnowledgeReasoner (encoder + bge + spaCy + live PG)...", flush=True)
    from engine.knowledge import KnowledgeReasoner
    Q = KnowledgeReasoner()
    from regress.live_schema import live_schema
    sub = live_schema().name

    by_cap = collections.defaultdict(lambda: collections.Counter())
    pred_hit = collections.Counter()
    detail = []
    for i, c in enumerate(cases):
        out = serve_case(Q, c, sub)
        verdict, why = classify(c, out)
        cap = c.get("capability", c.get("label", "?"))
        by_cap[cap][verdict] += 1
        # did reality match the designer's prediction?
        pred = c.get("prediction")
        works = verdict in ("PASS",)
        matched = (pred == "works" and works) or (pred in ("breaks", "unsupported") and not works)
        pred_hit["match" if matched else "miss"] += 1
        detail.append({"label": c["label"], "capability": cap, "question": c["question"],
                       "prediction": pred, "verdict": verdict, "why": why,
                       "scalar": out.get("scalar"), "clarify": out.get("clarify"),
                       "sql": out.get("sql"), "error": out.get("error")})
        print(f"  [{verdict:8s}] {c['label'][:48]:48s} pred={pred:11s} {why[:50]}")

    json.dump(detail, open(os.path.join(os.path.dirname(__file__), "world_capability_results.json"), "w"), indent=2)
    print("\n=== CAPABILITY MAP ===")
    for cap in sorted(by_cap):
        c = by_cap[cap]
        print(f"  {cap:34s} {dict(c)}")
    print(f"\nprediction accuracy: {dict(pred_hit)}")
    print("wrote regress/world_capability_results.json")


if __name__ == "__main__":
    main()
